nelmio_cors:
  defaults:
    allow_origin: [
        "http://localhost:5173",
        "http://44.204.158.131",
        "http://44.204.158.131:5173",
        "https://bistro-delight-aws.netlify.app",
         "http://bistro-delight-aws.netlify.app",
      ] # Replace with your React frontend's origin
    allow_headers: ["Content-Type", "Authorization"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin:
        [
          "http://localhost:5173",
          "http://44.204.158.131",
          "http://44.204.158.131:5173",
          "https://bistro-delight-aws.netlify.app",
           "http://bistro-delight-aws.netlify.app",
        ]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      max_age: 3600
