<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDHgtK5V\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDHgtK5V/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDHgtK5V.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDHgtK5V\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDHgtK5V\App_KernelProdContainer([
    'container.build_hash' => 'DHgtK5V',
    'container.build_id' => '43af347f',
    'container.build_time' => 1757107004,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDHgtK5V');
