<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'category_list' => [[], ['_controller' => 'App\\Controller\\CategoryController::list'], [], [['text', '/category']], [], [], []],
    'category_create' => [[], ['_controller' => 'App\\Controller\\CategoryController::create'], [], [['text', '/category/create']], [], [], []],
    'category_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category/edit']], [], [], []],
    'category_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::deleteCategory'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category/delete']], [], [], []],
    'app_dishes' => [[], ['_controller' => 'App\\Controller\\DishesController::index'], [], [['text', '/dishes']], [], [], []],
    'app_dish_create' => [[], ['_controller' => 'App\\Controller\\DishesController::create'], [], [['text', '/dish/create']], [], [], []],
    'app_dish' => [['id'], ['_controller' => 'App\\Controller\\DishesController::dish'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/dish']], [], [], []],
    'app_dish_edit' => [['id'], ['_controller' => 'App\\Controller\\DishesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/dish']], [], [], []],
    'app_dish_delete' => [['id'], ['_controller' => 'App\\Controller\\DishesController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/dish']], [], [], []],
    'api_dishes' => [[], ['_controller' => 'App\\Controller\\DishesController::dishes_list'], [], [['text', '/api/dishes']], [], [], []],
    'App\Controller\CategoryController::list' => [[], ['_controller' => 'App\\Controller\\CategoryController::list'], [], [['text', '/category']], [], [], []],
    'App\Controller\CategoryController::create' => [[], ['_controller' => 'App\\Controller\\CategoryController::create'], [], [['text', '/category/create']], [], [], []],
    'App\Controller\CategoryController::edit' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category/edit']], [], [], []],
    'App\Controller\CategoryController::deleteCategory' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::deleteCategory'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category/delete']], [], [], []],
    'App\Controller\DishesController::index' => [[], ['_controller' => 'App\\Controller\\DishesController::index'], [], [['text', '/dishes']], [], [], []],
    'App\Controller\DishesController::create' => [[], ['_controller' => 'App\\Controller\\DishesController::create'], [], [['text', '/dish/create']], [], [], []],
    'App\Controller\DishesController::dish' => [['id'], ['_controller' => 'App\\Controller\\DishesController::dish'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/dish']], [], [], []],
    'App\Controller\DishesController::edit' => [['id'], ['_controller' => 'App\\Controller\\DishesController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/dish']], [], [], []],
    'App\Controller\DishesController::delete' => [['id'], ['_controller' => 'App\\Controller\\DishesController::delete'], [], [['text', '/delete'], ['variable', '/', '[^/]++', 'id', true], ['text', '/dish']], [], [], []],
    'App\Controller\DishesController::dishes_list' => [[], ['_controller' => 'App\\Controller\\DishesController::dishes_list'], [], [['text', '/api/dishes']], [], [], []],
];
