<?php

namespace ContainerDHgtK5V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishesControllercreateService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AAtH1eF.App\Controller\DishesController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AAtH1eF.App\\Controller\\DishesController::create()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
        ], [
            'entityManager' => '?',
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
        ]))->withContext('App\\Controller\\DishesController::create()', $container);
    }
}
