<?php

namespace ContainerDHgtK5V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDishTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DishType' shared autowired service.
     *
     * @return \App\Form\DishType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DishType'] = new \App\Form\DishType();
    }
}
