<?php

namespace ContainerOcxzyvm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xr1wJmVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xr1wJmV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xr1wJmV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::list()', 'getCategoryControllerlistService', true],
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::create()', 'getCategoryControllercreateService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController::deleteCategory' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\DishesController::index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::index()', 'getDishesControllerindexService', true],
            'App\\Controller\\DishesController::create' => ['privates', '.service_locator.AAtH1eF.App\\Controller\\DishesController::create()', 'getDishesControllercreateService', true],
            'App\\Controller\\DishesController::dish' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::dish()', 'getDishesControllerdishService', true],
            'App\\Controller\\DishesController::edit' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::edit()', 'getDishesControllereditService', true],
            'App\\Controller\\DishesController::delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::delete()', 'getDishesControllerdeleteService', true],
            'App\\Controller\\DishesController::dishes_list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::dishes_list()', 'getDishesControllerdishesListService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::list()', 'getCategoryControllerlistService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::create()', 'getCategoryControllercreateService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::edit()', 'getCategoryControllereditService', true],
            'App\\Controller\\CategoryController:deleteCategory' => ['privates', '.service_locator.P.blNFL.App\\Controller\\CategoryController::deleteCategory()', 'getCategoryControllerdeleteCategoryService', true],
            'App\\Controller\\DishesController:index' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::index()', 'getDishesControllerindexService', true],
            'App\\Controller\\DishesController:create' => ['privates', '.service_locator.AAtH1eF.App\\Controller\\DishesController::create()', 'getDishesControllercreateService', true],
            'App\\Controller\\DishesController:dish' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::dish()', 'getDishesControllerdishService', true],
            'App\\Controller\\DishesController:edit' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::edit()', 'getDishesControllereditService', true],
            'App\\Controller\\DishesController:delete' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::delete()', 'getDishesControllerdeleteService', true],
            'App\\Controller\\DishesController:dishes_list' => ['privates', '.service_locator.P.blNFL.App\\Controller\\DishesController::dishes_list()', 'getDishesControllerdishesListService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::list' => '?',
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::deleteCategory' => '?',
            'App\\Controller\\DishesController::index' => '?',
            'App\\Controller\\DishesController::create' => '?',
            'App\\Controller\\DishesController::dish' => '?',
            'App\\Controller\\DishesController::edit' => '?',
            'App\\Controller\\DishesController::delete' => '?',
            'App\\Controller\\DishesController::dishes_list' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:list' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:deleteCategory' => '?',
            'App\\Controller\\DishesController:index' => '?',
            'App\\Controller\\DishesController:create' => '?',
            'App\\Controller\\DishesController:dish' => '?',
            'App\\Controller\\DishesController:edit' => '?',
            'App\\Controller\\DishesController:delete' => '?',
            'App\\Controller\\DishesController:dishes_list' => '?',
        ]);
    }
}
