<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKuL5UGk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKuL5UGk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKuL5UGk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKuL5UGk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKuL5UGk\App_KernelDevDebugContainer([
    'container.build_hash' => 'KuL5UGk',
    'container.build_id' => 'a3be0191',
    'container.build_time' => 1757103115,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKuL5UGk');
