<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOcxzyvm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOcxzyvm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOcxzyvm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOcxzyvm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOcxzyvm\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ocxzyvm',
    'container.build_id' => 'a3e0b285',
    'container.build_time' => 1757187688,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOcxzyvm');
